Design
StianJohnsen/dte2503_team_3_repo pull request #30
Opened 2023-10-31 14:47 UTC by yevhenverkhalantsev

2023-11-01 11:44 UTC, ysz0507 requested changes
This ticket does not feel like it is ready for review. There are a few things you probably already know on your own. But even if it might be annoying, things like the resources are really obvious to Alexander. So we must change it before merging. 

Btw. imagine I just approved and merged the branch. Would you be happy with the codebase?

2023-11-01 11:44 UTC, ysz0507 commented on app/src/main/res/drawable/ic_circle_start_recording.webp
This file already exists with the name `ic_circle_recording.webp`. If you want to change the icon, then you should delete the old one.

2023-11-01 11:44 UTC, ysz0507 commented on app/src/main/res/drawable/ic_dashcam_settings2.webp
You should **never** add the same icon twice. Just reuse the existing one. Btw. ideally, icons should have as little padding as possible on the sides because it is more flexible to add the padding in the code if you need it. If you don't like an existing resource you can change it. But don't just add a copy.

2023-11-01 11:44 UTC, ysz0507 commented on app/src/main/res/drawable/ic_triangle_settings.webp
Don't add already existing resources

2023-11-01 11:44 UTC, ysz0507 commented on app/src/main/res/drawable/logo.webp
Ideally, you want way less padding on the logo

2023-11-01 11:44 UTC, ysz0507 commented on app/src/main/res/layout/fragment_recording_statistics.xml
The line is really thin. I almost can't see it. It looks like a graphics bug to the user. So make it less thin 
<img width="366" alt="image" src="https://github.com/StianJohnsen/dte2503_team_3_repo/assets/57566364/2b15722c-9ac4-496e-a7cb-2994b8ef4eee">

2023-11-01 11:44 UTC, ysz0507 commented on app/src/main/res/layout/fragment_recording_statistics.xml
Although it was not originally included in your ticket it would be nice to improve the text size of the graph in this branch, because it fits really well. It shouldn't take much time because it is already implemented in the recording details fragment. Here is an important snippet:
```
val legend = lineChart.legend
legend.textColor = Color.WHITE
legend.isEnabled = true
legend.textSize = 16F
legend.formSize = 16F
```

2023-11-02 12:39 UTC, yevhenverkhalantsev commented on app/src/main/java/com/example/dashcarr/presentation/MainActivity.kt
> +        val colorStateList = ColorStateList.valueOf(ContextCompat.getColor(this, R.color.mainBlue))
Normal: Gray icons, No Text
Selected: Blue Icon, Blue Text
Button in the middle Blue
done.

2023-11-02 12:41 UTC, yevhenverkhalantsev commented on app/src/main/res/drawable/ic_circle_start_recording.webp
ic_circle_recording.webp deleted

2023-11-02 12:47 UTC, yevhenverkhalantsev commented on app/src/main/res/drawable/ic_dashcam_settings2.webp
ic_dashcam_settings2.webp deleted

2023-11-02 12:50 UTC, yevhenverkhalantsev commented on app/src/main/res/drawable/ic_triangle_settings.webp
there are both on usage. keep them
ic_triangle_settings.webp
ic_triangle_recording.webp

2023-11-02 12:56 UTC, yevhenverkhalantsev commented on app/src/main/res/drawable/logo.webp
done

2023-11-02 13:01 UTC, yevhenverkhalantsev commented on app/src/main/res/layout/fragment_recording_statistics.xml
0.75dp instead of 0.5dp 
grey3 instead of gray2

2023-11-05 13:33 UTC, ysz0507 approved these changes
Nice looks good :)
Just one small thing about the files 
- ic_triangle_settings.webp
- ic_triangle_recording.webp

We can talk about it on Tuesday :)

2023-11-05 13:35 UTC, merged