Fix recording
StianJohnsen/dte2503_team_3_repo pull request #9
Opened 2023-10-11 15:34 UTC by StianJohnsen

Have gotten recording to work.
Saves accelerometer/gyroscope and location data to a .csv file.
Saves information about the data in a .json file.
Checkboxes work for configuring the recording.
Recording control (pause/resume, stop and delete buttons) also work

2023-10-12 00:19 UTC, ysz0507 requested changes
I think that is enough for this review. We have to talk about what has to be done tomorrow in detail. When you are done I will give you another review. So far I like your ideas 👍

2023-10-12 00:19 UTC, ysz0507 commented on app/src/main/res/layout/fragment_recording.xml
We have to talk about the design tomorrow. I am not sure what out target is

2023-10-12 00:19 UTC, ysz0507 commented on app/src/main/res/layout/fragment_recording.xml
There are a few Bugs:
- back button does not work
- crash though going backwards
- the checkboxes do not work

2023-10-12 00:19 UTC, ysz0507 commented on app/src/main/java/com/example/dashcarr/presentation/tabs/settings/ConfigureRecordingFragment.kt
Really important: make a rebase manually on your computer an fix the errors that will occur.

2023-10-12 00:19 UTC, ysz0507 commented on app/src/main/java/com/example/dashcarr/presentation/tabs/settings/ConfigureRecordingFragment.kt
> +         */
remove commented code

2023-10-12 00:19 UTC, ysz0507 commented on app/src/main/java/com/example/dashcarr/presentation/tabs/settings/ConfigureRecordingFragment.kt
>      private var startTimeMillis: Long = 0
you are not using this variable

2023-10-12 00:19 UTC, ysz0507 commented on app/src/main/java/com/example/dashcarr/presentation/tabs/settings/ConfigureRecordingFragment.kt
>          inflater: LayoutInflater, container: ViewGroup?,
Your IDE is highlighting some stuff yellow. It is most of the time very useful to implement it to get cleaner code. Here as well you don't have to check for null twice

2023-10-12 00:19 UTC, ysz0507 commented on app/src/main/java/com/example/dashcarr/presentation/tabs/settings/ConfigureRecordingFragment.kt
>      fun startRecording() {
Yellow again (private)
Just fix everything that's yellow

2023-10-12 00:19 UTC, ysz0507 commented on app/src/main/java/com/example/dashcarr/presentation/tabs/settings/RecordingFragment.kt
> +    //private val viewModel: RecordingViewModel by viewModels()
remove comment

2023-10-12 00:19 UTC, ysz0507 commented on app/src/main/java/com/example/dashcarr/presentation/tabs/settings/RecordingFragment.kt
> +         */
remove

2023-10-12 00:19 UTC, ysz0507 commented on app/src/main/java/com/example/dashcarr/presentation/tabs/settings/RecordingFragment.kt
> +        //settingsViewModel.isFilteredChecked.collect {}.cancel()
remove function override

2023-10-12 00:19 UTC, ysz0507 commented on app/src/main/java/com/example/dashcarr/presentation/tabs/settings/RecordingFragment.kt
> +    private var pauseTimeMillis: Long = 0
never used

2023-10-12 15:20 UTC, QuentinRG approved these changes
Well done! nothing to say, no warnings and it's working

2023-10-13 10:17 UTC, ysz0507 approved these changes
nice

2023-10-13 10:17 UTC, merged